# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fbcc6589aa22d4333904fade7f9575fa62c2b8c549586cc61118038e94e53ce9a26d555e0fcf2a46a8f659d88d4f795e5b8f36c81dd4301b33c22d190d8281e3

test:
  secret_key_base: 85d58ff4712f7c1b95c2e8092d132d98e1132a81fb59e1b8cd4d70d44a90a6472617b89c8f876e6a9982c2aa763713113c2782b73e3d01d8f68bd8479c87d349

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
